### ISSUE TITLE
Switch to Netlify

### ISSUE THREAD

**Issue by msiebuhr** [msiebuhr/charcod.es#59]
Netlify is a freemium static site hosting service, that can take care of building, serving (including HTTPS) for us.

Reasons to switch:
 * Get HTTPS. GratisDNS + Github Pages doesn't do that, and we'll need it to get some of the new web features to work
 * The current build-pipeline is quite fragile and I keep forgetting how it works.

Reasons for Netlify:
 * Cloudflare + gh-pages would solve the HTTP-problem, but leave the build-pipeline. Also, CF requires that their DNS servers take care of charcod.es, which GratisDNS doesn't allow us to do without paying some rather hefty fees.
 * Netlify runs a build-pipeline that magically does the right thing for us

## TODO
 * [x] Switch to Netlify
 * [x] Get HTTPS working
 * [x] Clean up old build-pipeline
 * [x] Do a `release`-branch for Netlify to track.

**Comment by msiebuhr** [comment]
Related to #58

**Comment by msiebuhr** [comment]
Found out we were publishing `http-pub` and not `http-pub-production`...

**Comment by msiebuhr** [comment]
Also added @Munter and @omichelsen as site administrators on Netlify.

**Comment by msiebuhr** [comment]
From the console messages, it looks like Google Analytics is broken when used over HTTPS.

Perhaps we should just switch to something else, if we're tinkering with it any way. Opinions?

**Comment by papandreou** [comment]
> From the console messages, it looks like Google Analytics is broken when used over HTTPS

Fixed in 7f4e8080e100f70c61b58ab47df82c44bdfbcb5e

**Comment by papandreou** [comment]
Switch to something other than netlify? Why would we do that? Is there something better?

**Comment by msiebuhr** [comment]
I was thinking about switching to something else than Google Analytics...

**Comment by papandreou** [comment]
Oh... :)

**Comment by msiebuhr** [comment]
Also, releases are now done from the `release` branch. Fast-forward merge into master and push...

**Comment by papandreou** [comment]
Thanks. I managed to deploy 7f4e8080e100f70c61b58ab47df82c44bdfbcb5e via the netlify web interface, but will use `release` from now on. Fast-forward merged it just now.

**Comment by msiebuhr** [comment]
No worries. If we rather want a Netlify-based workflow, I'm OK with that.

**Comment by papandreou** [comment]
Pushing a branch is nicer, I just didn't know any better :)
